### ISSUE TITLE
notebook with predictions for demo account

### ISSUE THREAD

**Issue by waudinio27** [sydney-machine-learning/Bayesianneuralnet_stockmarket#1]
Hello Chandra - I have read the paper in PLOS ONE and it looks promising. 
Are you planning to put a jupyter notebook here as well that shows everything together in one place? 
It should include a part that shows the real predictions after the train test part so one can try your code in real life with a demo account.

Greetings and thanks

**Comment by rohitash-chandra** [comment]
Sorry I don't have time now, feel free to extend it further.
